version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mock-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./prometheus/mysql-init:/docker-entrypoint-initdb.d   # <<< THIS LINE ADDED
                                                               # points to SQL initialization folder
  
  exporter:
    build: ./exporter
    container_name: metrics-exporter
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - BACKUP_FILE_PATH=/backup/backup.sql
    volumes:
      - backup-data:/backup
    ports:
      - "8000:8000"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  backup-data:

